/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Court } from "./Court";
import { CourtCountArgs } from "./CourtCountArgs";
import { CourtFindManyArgs } from "./CourtFindManyArgs";
import { CourtFindUniqueArgs } from "./CourtFindUniqueArgs";
import { DeleteCourtArgs } from "./DeleteCourtArgs";
import { CourtService } from "../court.service";
@graphql.Resolver(() => Court)
export class CourtResolverBase {
  constructor(protected readonly service: CourtService) {}

  async _courtsMeta(
    @graphql.Args() args: CourtCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Court])
  async courts(@graphql.Args() args: CourtFindManyArgs): Promise<Court[]> {
    return this.service.courts(args);
  }

  @graphql.Query(() => Court, { nullable: true })
  async court(
    @graphql.Args() args: CourtFindUniqueArgs
  ): Promise<Court | null> {
    const result = await this.service.court(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Court)
  async deleteCourt(
    @graphql.Args() args: DeleteCourtArgs
  ): Promise<Court | null> {
    try {
      return await this.service.deleteCourt(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
